class NoPositiveIntegerPropensityToBuyException(Exception): ...
class NoProbabilityPropensityToAddSupplementException(Exception): ...
class NoPositiveCOGSException(Exception): ...
class NoPositivePriceException(Exception): ...
class NoPositiveInventorySurplusException(Exception): ...
class NonUniqueProductIdsException(Exception): ...
class NoProductsException(Exception): ...