class NoPositiveIntegerPropensityToBuyException(Exception): ...
class NoProbabilityPropensityToAddSupplementException(Exception): ...
class NoPositiveCOGSException(Exception): ...
class NoPositivePriceException(Exception): ...
class NoPositiveInventoryException(Exception): ...
class NonUniqueProductIdsException(Exception): ...
class NoProductsException(Exception): ...
class TooSmallInventoryLevelException(Exception): ...