class NonPositiveMinInventoryException(Exception): ...
class NonPositiveRestockAmountException(Exception): ...
class NonPercentageClubMemberDiscountException(Exception): ...
class NonProbabilityIsMemberProbException(Exception): ...
class NonPositiveSupplementsCostException(Exception): ...
class EmptyTransactionItemsWeights(Exception): ...
class EmptyTransactionQuantityWeights(Exception): ...
class NonPositiveTransactionItemsWeightException(Exception): ...
class NonPositiveTransactionQuantityWeightException(Exception): ...

class NonPositiveMinSaleFrequenceException(Exception): ...
class NonPositiveMaxSaleFrequencyException(Exception): ...
class NonPositiveNumSalesException(Exception): ...
class MinMaxSaleFrequencyException(Exception): ...