class NonPositiveMinSaleFrequenceException(Exception): ...
class NonPositiveMaxSaleFrequencyException(Exception): ...
class NonPositiveNumSalesException(Exception): ...
class MinMaxSaleFrequencyException(Exception): ...
class EmptyTransactionItemsWeights(Exception): ...
class NonPositiveTransactionItemsWeightException(Exception): ...